name: Generator

on:
  workflow_dispatch:
  push:
    branches: [generator]

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      buildnumber: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Number
        run: echo "Build Number - $BUILD_NUMBER"

      - uses: actions/checkout@v4
        with:
          ref: generator

      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0

      - name: Setup Git
        shell: bash
        run: |
          set -e

          git config --global user.email "noop@github.com"
          git config --global user.name "action"
          git config --global url."https://${{ secrets.REPO_USER }}:${{ secrets.REPO_TOKEN }}@github.com/".insteadOf https://github.com/

      - name: Get Dependencies
        run: |
          mkdir deps
          cd deps
          git clone https://github.com/googleapis/googleapis
          git clone https://github.com/grafeas/grafeas

          rm -rf googleapis/google/ads
          rm -rf googleapis/google/chromeos
          rm -rf googleapis/google/cloud
          rm -rf googleapis/google/example
          rm -rf googleapis/google/shopping
          rm -rf googleapis/grafeas/v1alpha1
          rm -rf googleapis/grafeas/v1beta1

          rm -rf grafeas/proto/v1alpha1
          rm -rf grafeas/proto/v1beta1

      - name: Generate Dart Files
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          dart pub global activate protoc_plugin
          ls -l ~/.pub-cache/bin
          echo "$PATH"
          dart pub get
          mkdir generated
          cd generated
          git clone https://github.com/peiffer-innovations/grpc_googleapis .
          cd ..
          dart tool/generate.dart $BUILD_NUMBER
          cd generated
          dart pub get
          dart format lib
          dart analyze

      - name: Update main
        run: |
          git config --global user.email "noop@github.com"
          git config --global url."https://action:${{secrets.REPO_TOKEN}}@github.com/".insteadOf https://github.com/
          git add .
          git commit -m "Updates"
          git push origin
        working-directory: generated