name: Publisher

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.1.2
        with:
          flutter_package: false

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true

      - uses: peiffer-innovations/actions-dart-version-autotag@v1.0.1
        with:
          token: ${{ secrets.REPO_TOKEN }}
